/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Smart Hire AI API
 * API documentation for the Smart Hire AI backend
 * OpenAPI spec version: v1
 */

export interface Candidate {
  id?: number;
  fullName?: string;
  email?: string;
  experienceYears?: number;
  educationLevel?: string;
  skills?: string[];
}
