/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Smart Hire AI API
 * API documentation for the Smart Hire AI backend
 * OpenAPI spec version: v1
 */

export * from './candidate';
export * from './createCandidateRequest';
export * from './createJobRequest';
export * from './job';
