/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Smart Hire AI API
 * API documentation for the Smart Hire AI backend
 * OpenAPI spec version: v1
 */

export interface Job {
  id?: number;
  title?: string;
  company?: string;
  minimumExperienceYears?: number;
  educationLevel?: string;
  requiredSkills?: string[];
}
