apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: smart-hire-ai
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/lmazlouly/smart-hire-ai
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
