  backen/.env

spring.application.name=smart-hire-ai-backend
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
security.jwt.expiration-ms=86400000
security.jwt.secret=UZqzFZ0I

spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=69c42e02d938c852509bd798edc0643aeaf192c3b190676ed5dfa4020d3657b7
spring.datasource.password=sk_m-eUZqzr2FL3Y7qjdFZ0I
security.jwt.secret=Zjnbli59GyXDeEa7ap5jNa3cSp0EZWBdH1kuWiC2Sww=
security.jwt.expiration-ms=86400000

spring.application.name=smart-hire-ai-backend
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
security.jwt.expiration-ms=86400000
security.jwt.secret=UZqzFZ0I



cloudflare.r2.access-key=TON_ACCESS_KEY
cloudflare.r2.secret-key=TON_SECRET_KEY
cloudflare.r2.bucket-name=smarthireai
cloudflare.r2.endpoint=https://1e628ba0042c7e547daaee89ff2101b6.r2.cloudflarestorage.com
cloudflare.r2.public-url=https://shaicdn.onixellc.com